In [16]:
from pymatgen import core
from pymatgen.core import sites
from pymatgen.symmetry import analyzer
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.io.smartio import read_structure, write_structure
from pymatgen.io import vaspio_set
import os
import shutil
import copy
import numpy as np
from pymatgen.transformations import standard_transformations


In [3]:
s1 = read_structure("POSCAR-1998.vasp")

-c:1: DeprecationWarning: read_structure is deprecated; use from_file in pymatgen.core.structure instead.


In [4]:
s1

Structure Summary
Lattice
    abc : 32.456001281699997 5.6739997863999996 3.9949998856
 angles : 90.0 90.0 90.0
 volume : 735.70057956998539
      A : 32.456001281699997 0.0 0.0
      B : 0.0 5.6739997863999996 0.0
      C : 0.0 0.0 3.9949998856
PeriodicSite: Sr (6.9764, 3.1901, 1.9975) [0.2149, 0.5622, 0.5000]
PeriodicSite: Sr (25.4796, 2.4839, 1.9975) [0.7851, 0.4378, 0.5000]
PeriodicSite: Sr (9.2516, 0.3531, 0.0000) [0.2851, 0.0622, 0.0000]
PeriodicSite: Sr (23.2044, 5.3209, 0.0000) [0.7149, 0.9378, 0.0000]
PeriodicSite: Sr (16.2280, 0.0000, 0.0000) [0.5000, 0.0000, 0.0000]
PeriodicSite: Sr (0.0000, 2.8370, 1.9975) [0.0000, 0.5000, 0.5000]
PeriodicSite: Sr (13.2649, 2.7446, 0.0000) [0.4087, 0.4837, 0.0000]
PeriodicSite: Sr (19.1911, 2.9294, 0.0000) [0.5913, 0.5163, 0.0000]
PeriodicSite: Sr (2.9631, 5.5816, 1.9975) [0.0913, 0.9837, 0.5000]
PeriodicSite: Sr (29.4929, 0.0924, 1.9975) [0.9087, 0.0163, 0.5000]
PeriodicSite: Nb (16.2280, 2.8370, 1.9975) [0.5000, 0.5000, 0.5000]
PeriodicSi

In [18]:
rotateTrans = standard_transformations.RotationTransformation([0, 0, 1], 45, angle_in_radians=False)

In [23]:
s1_rotate = rotateTrans.apply_transformation(s1)

In [24]:
s1_rotate

Structure Summary
Lattice
    abc : 32.456001281699997 5.6739997864000005 3.9949998856
 angles : 90.0 90.0 90.0
 volume : 735.70057956998539
      A : 22.949858596489346 22.949858596489342 0.0
      B : -4.0121237254144617 4.0121237254144626 0.0
      C : 0.0 0.0 3.9949998856
PeriodicSite: Sr (2.6773, 7.1888, 1.9975) [0.2149, 0.5622, 0.5000]
PeriodicSite: Sr (16.2604, 19.7732, 1.9975) [0.7851, 0.4378, 0.5000]
PeriodicSite: Sr (6.2922, 6.7916, 0.0000) [0.2851, 0.0622, 0.0000]
PeriodicSite: Sr (12.6455, 20.1704, 0.0000) [0.7149, 0.9378, 0.0000]
PeriodicSite: Sr (11.4749, 11.4749, 0.0000) [0.5000, 0.0000, 0.0000]
PeriodicSite: Sr (-2.0061, 2.0061, 1.9975) [-0.0000, 0.5000, 0.5000]
PeriodicSite: Sr (7.4390, 11.3204, 0.0000) [0.4087, 0.4837, 0.0000]
PeriodicSite: Sr (11.4987, 15.6416, 0.0000) [0.5913, 0.5163, 0.0000]
PeriodicSite: Sr (-1.8515, 6.0420, 1.9975) [0.0913, 0.9837, 0.5000]
PeriodicSite: Sr (20.7893, 20.9200, 1.9975) [0.9087, 0.0163, 0.5000]
PeriodicSite: Nb (9.4689, 13.4810, 1.99

In [25]:
write_structure(s1_rotate,"POSCAR")

-c:1: DeprecationWarning: write_structure is deprecated; use to in pymatgen.core.structure instead.


# 

# strain s1

In [30]:
for i in my_range(-0.03,0.03,0.03):
    for j in my_range(-0.03,0.03,0.03):
        for k in my_range(-0.03,0.03,0.03):
            s1_new = copy.deepcopy(s1)
            strain = [i,j,k]
            s1_new.apply_strain(strain)
            currentFolder = "strain_" + "{:4.2f}".format(i) + "_" + "{:4.2f}".format(j) + "_" + "{:4.2f}".format(k)
            if os.path.exists(currentFolder):
                shutil.rmtree(currentFolder)
            os.mkdir(currentFolder)
            write_structure(s1_new,"POSCAR")
            shutil.copy("POSCAR", currentFolder + "/POSCAR")
            shutil.copy("INCAR", currentFolder + "/INCAR")
            shutil.copy("KPOINTS", currentFolder + "/KPOINTS")
            shutil.copy("POTCAR", currentFolder + "/POTCAR")

In [28]:
def my_range(start, end, step):
	while start <= end:
		yield start
		start += step

In [865]:
s1_new

Structure Summary
Lattice
    abc : 5.7235764553842321 5.8904898364380323 8.216099391271543
 angles : 90.0 90.0 90.0
 volume : 277.00307094266981
      A : 5.7235764553842321 0.0 0.0
      B : 0.0 5.8904898364380323 0.0
      C : 0.0 0.0 8.216099391271543
PeriodicSite: Sr (5.7015, 0.1786, 2.0540) [0.9961, 0.0303, 0.2500]
PeriodicSite: Sr (2.8839, 3.1238, 2.0540) [0.5039, 0.5303, 0.2500]
PeriodicSite: Sr (2.8397, 2.7666, 6.1621) [0.4961, 0.4697, 0.7500]
PeriodicSite: Sr (0.0221, 5.7119, 6.1621) [0.0039, 0.9697, 0.7500]
PeriodicSite: Nb (2.8618, 0.0001, 4.1077) [0.5000, 0.0000, 0.5000]
PeriodicSite: Nb (-0.0000, 2.9452, -0.0003) [-0.0000, 0.5000, -0.0000]
PeriodicSite: Nb (-0.0000, 2.9452, 4.1084) [-0.0000, 0.5000, 0.5000]
PeriodicSite: Nb (2.8618, 0.0001, 0.0003) [0.5000, 0.0000, 0.0000]
PeriodicSite: O (1.5534, 4.1613, 4.3097) [0.2714, 0.7064, 0.5245]
PeriodicSite: O (1.3084, 1.2160, 8.0144) [0.2286, 0.2064, 0.9755]
PeriodicSite: O (4.4152, 4.6745, 3.9064) [0.7714, 0.7936, 0.4755]
Peri

In [867]:
trans_O_Nb

[array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00]),
 array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00]),
 array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00]),
 array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00]),
 array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00]),
 array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00]),
 array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00]),
 array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00]),
 array([-1.63520477, -1.28007148, -0.21196061]),
 array([ 1.63514467, -1.27995006,  0.21263556]),
 array([-1.63522509,  1.28008418,  0.21196178]),
 array([ 1.6351724 ,  1.27996217, -0.21262971]),
 array([ 1.63514467,  1.27995006,  0.21263556]),
 array([-1.63520477,  1.28007148, -0.21196061]),
 array([ 1.6351724 , -1.27996217, -0.21262971]),
 array([-1.63522509, -1.28008418,  0.21196178]),
 array([-5.4383163 , -0.06470056,  2.05369594]),
 array([ -2.19805063e-05,   2.94518393e+00,   8

## other...

In [869]:
O

PeriodicSite: O (5.4383, 3.0099, 6.1621) [0.9502, 0.5110, 0.7500]

In [870]:
Nb

PeriodicSite: Nb (-0.0000, 2.9452, 8.2158) [-0.0000, 0.5000, 1.0000]

In [871]:
O_p

array([ 5.43829432,  3.00988449,  6.16207069])

In [872]:
Nb_p

array([ -2.19805063e-05,   2.94518393e+00,   8.21576663e+00])

##### 

In [884]:
sga = SpacegroupAnalyzer(s1, 0.01)

In [885]:
sga.get_spacegroup_symbol()

u'Pbnm'

In [875]:
s2_sym = sga.get_symmetrized_structure()

In [876]:
s2_sym.equivalent_sites

[[PeriodicSite: Sr (5.6724, 0.2167, 2.0506) [0.9911, 0.0368, 0.2496],
  PeriodicSite: Sr (2.9130, 3.1620, 2.0575) [0.5089, 0.5368, 0.2504],
  PeriodicSite: Sr (2.8106, 2.7285, 6.1586) [0.4911, 0.4632, 0.7496],
  PeriodicSite: Sr (0.0512, 5.6738, 6.1655) [0.0089, 0.9632, 0.7504]],
 [PeriodicSite: Nb (2.8618, 5.8905, 4.1080) [0.5000, 1.0000, 0.5000],
  PeriodicSite: Nb (5.7236, 2.9452, 8.2161) [1.0000, 0.5000, 1.0000]],
 [PeriodicSite: Nb (5.7236, 2.9453, 4.1081) [1.0000, 0.5000, 0.5000],
  PeriodicSite: Nb (2.8618, 5.8905, 0.0000) [0.5000, 1.0000, 0.0000]],
 [PeriodicSite: O (1.6564, 4.2049, 4.4154) [0.2894, 0.7138, 0.5374],
  PeriodicSite: O (1.2054, 1.2596, 7.9088) [0.2106, 0.2138, 0.9626],
  PeriodicSite: O (4.0672, 1.6856, 3.8007) [0.7106, 0.2862, 0.4626],
  PeriodicSite: O (4.5182, 4.6309, 0.3073) [0.7894, 0.7862, 0.0374]],
 [PeriodicSite: O (4.5531, 4.5790, 3.7980) [0.7955, 0.7774, 0.4623],
  PeriodicSite: O (4.0323, 1.6338, 0.3101) [0.7045, 0.2774, 0.0377],
  PeriodicSite: O (1.1

In [877]:
sym_op = sga.get_symmetry_operations()

In [878]:
sym_op_cart = sga.get_symmetry_operations(cartesian = True)

In [879]:
sym_op_cart

[Rot:
 [[ 1.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0.  1.]]
 tau
 [ 0.  0.  0.], Rot:
 [[-1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0. -1.]]
 tau
 [  1.18698675e-06   0.00000000e+00   1.60980393e-08], Rot:
 [[-1.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0. -1.]]
 tau
 [ 2.86178941  2.94524492  4.10804971], Rot:
 [[ 1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0.  1.]]
 tau
 [ 2.86178823  2.94524492  4.1080497 ]]

In [880]:
sym_op_cart_all = analyzer.generate_full_symmops(sym_op_cart, 0)

In [881]:
len(sym_op_cart)

4

In [882]:
len(sym_op_cart_all)

301

# write inputs

In [882]:
vaspio_set.batch_write_vasp_input