In [135]:
import numpy as np
pcell = np.array([[8.5315969999999997,    0.0000000000000000,    0.0000000000000000],
     [4.2657990000000003,    7.3885800000000001,    0.0000000000000000],
     [4.2657990000000003,   2.4628600000000000,    6.9660200000000003]])

In [136]:
tetra = np.array([[8.5315969999999997, 0, 0],
                 [0, 8.5315969999999997, 0],
                 [0, 0, 12.06550018]])

In [137]:
trans = np.array([[1, 0, 0],
                  [0, -1, 1],
                  [-1, 1, 1]])

In [138]:
u, s, v = np.linalg.svd(trans.dot(pcell))

In [139]:
trans_new = np.linalg.inv(u).dot(trans)

In [140]:
atoms = np.array([[0.2500000000000000,  0.2500000000000000,  0.2500000000000000],
  [0.7500000000000000,  0.7500000000000000,  0.7500000000000000],
  [0.0000000000000000,  0.0000000000000000,  0.0000000000000000],
  [0.7587570000000028,  0.7587570000000028,  0.2412429999999972],
  [0.2412429999999972,  0.7587570000000028,  0.7587570000000028],
  [0.7587570000000028,  0.2412429999999972,  0.2412429999999972],
  [0.2412429999999972,  0.2412429999999972,  0.7587570000000028],
  [0.7587570000000028,  0.2412429999999972,  0.7587570000000028],
  [0.2412429999999972,  0.7587570000000028,  0.2412429999999972]])

In [141]:
atoms_tetra = atoms.dot(np.linalg.inv(trans_new))

In [142]:
float_formatter = lambda x: "%.6f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})

In [143]:
atoms_tetra[:,[0, 1, 2]] = atoms_tetra[:,[2, 1, 0]]
atoms_tetra

array([[-0.500000, 0.000000, 0.250000],
       [-1.500000, 0.000000, 0.750000],
       [0.000000, 0.000000, 0.000000],
       [-1.258757, -0.258757, 0.500000],
       [-1.000000, 0.000000, 0.758757],
       [-1.000000, 0.000000, 0.241243],
       [-0.741243, 0.258757, 0.500000],
       [-1.258757, 0.258757, 0.500000],
       [-0.741243, -0.258757, 0.500000]])

In [144]:
superatoms = np.zeros((9*125, 3))
for i in range(-2,3):
    for j in range(-2,3):
        for k in range(-2,3):
            superatoms[9*(25*(i+2)+5*(j+2)+(k+2)):9*(25*(i+2)+5*(j+2)+(k+2))+9,:] = atoms+np.array([i, j, k])

In [145]:
superatoms_tetra = superatoms.dot(np.linalg.inv(trans_new))
superatoms_tetra[:,[0, 1, 2]] = superatoms_tetra[:,[2, 1, 0]]
for i in range(9*81):
    if superatoms_tetra[i,0]>-0.01 and superatoms_tetra[i,0]<0.99 \
    and superatoms_tetra[i,1]>-0.01 and superatoms_tetra[i,1]<0.99\
    and superatoms_tetra[i,2]>-0.01 and superatoms_tetra[i,2]<0.99:
        print(superatoms_tetra[i,:])

[0.741243 0.741243 0.500000]
[0.500000 -0.000000 0.750000]
[0.741243 0.258757 0.500000]
[0.500000 0.500000 0.741243]
[0.000000 0.500000 0.250000]
[0.241243 0.241243 -0.000000]
[0.500000 0.500000 0.258757]
[0.758757 0.758757 -0.000000]
[0.241243 0.758757 -0.000000]
[0.758757 0.241243 -0.000000]
[0.258757 0.741243 0.500000]
[0.500000 -0.000000 0.250000]
[0.000000 0.000000 0.758757]
[0.000000 0.000000 0.241243]
[0.258757 0.258757 0.500000]
[0.000000 0.500000 0.750000]
[0.500000 0.500000 0.500000]
[0.000000 0.000000 0.000000]
